Update links in the README
redhat-cop/cloud.aws_ops pull request #111
Opened 2024-04-22 18:18 UTC by GomathiselviS

This PR corrects some of the incorrect links and updates all links to relative ones.

2024-04-22 20:57 UTC, mandar242 commented on README.md
> +[cloud.backup_select_resources](roles/backup_create_plan/README.md)|A role to select resources to back up with an existing backup plan.
```suggestion
[cloud.backup_select_resources](roles/backup_select_resources/README.md)|A role to select resources to back up with an existing backup plan.
```

2024-04-22 21:01 UTC, mandar242 approved these changes

2024-04-23 01:14 UTC, hakbailey requested changes

2024-04-23 01:14 UTC, hakbailey commented on playbooks/move_vm_from_on_prem_to_aws/README.md
> +This playbook uses the ``cloud.aws_ops.clone_on_prem_vm`` role to clone an existing VM on prem using the KVM hypervisor and the ``cloud.aws_ops.import_image_and_run_aws_instance`` role to import a lo
```suggestion
This playbook uses the ``cloud.aws_ops.clone_on_prem_vm`` role to clone an existing VM on prem using the KVM hypervisor and the ``cloud.aws_ops.import_image_and_run_aws_instance`` role to import a local .raw image into an Amazon machine image (AMI) and run an AWS EC2 instance. For a complete list of requirements, see [clone_on_prem_vm](../../roles/clone_on_prem_vm/README.md#Requirements) and [import_image_and_run_aws_instance](../../roles/import_image_and_run_aws_instance/README.md#Requirements), respectively.
```

2024-04-23 01:14 UTC, hakbailey commented on playbooks/move_vm_from_on_prem_to_aws/README.md
> +For a full list of accepted variables see: [clone_on_prem_vm](../../roles/clone_on_prem_vm/README.md#Role-Variables) and respectively [import_image_and_run_aws_instance](../../roles/import_image_and_
```suggestion
For a full list of accepted variables see: [clone_on_prem_vm](../../roles/clone_on_prem_vm/README.md#Role-Variables) and respectively [import_image_and_run_aws_instance](../../roles/import_image_and_run_aws_instance/README.md#Role-Variables).
```

2024-04-23 01:14 UTC, hakbailey commented on roles/awsconfig_apigateway_with_lambda_integration/README.md
> +See [LICENCE](../../LICENSE) to see the full text.
```suggestion
See [LICENSE](../../LICENSE) to see the full text.
```

2024-04-23 01:14 UTC, hakbailey commented on roles/awsconfig_apigateway_with_lambda_integration/README.md
> +See [LICENCE](../../LICENSE) to see the full text.
There are a bunch more cases of this typo below that we should probably update.

2024-04-23 15:57 UTC, alinabuzachis approved these changes

2024-04-23 16:00 UTC, alinabuzachis commented
Unrelated to this PR, but the integration tests fails with:

```
fatal: [testhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'arn'\n\nThe error appears to be in '/home/runner/collections/ansible_collections/cloud/aws_ops/roles/backup_select_resources/tasks/main.yaml': line 54, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set backup role ARN\n      ^ here\n"
}
```

Would you like to have a look in this PR @GomathiselviS? The fix might be trivial.

2024-04-24 20:26 UTC, GomathiselviS commented
> Unrelated to this PR, but the integration tests fail with:
> 
> ```
> fatal: [testhost]: FAILED! => {
>     "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'arn'\n\nThe error appears to be in '/home/runner/collections/ansible_collections/cloud/aws_ops/roles/backup_select_resources/tasks/main.yaml': line 54, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set backup role ARN\n      ^ here\n"
> }
> ```
> 
> Would you like to have a look in this PR @GomathiselviS? The fix may be trivial.

I will work on this in a separate PR. Thank you for pointing out the failure.

2024-04-26 17:04 UTC, merged