manage_vpc_peering: fix integration tests
redhat-cop/cloud.aws_ops pull request #61
Opened 2023-07-12 21:02 UTC by mandar242

Fix integration tests for `manage_vpc_peering` role.

2023-07-13 13:43 UTC, gravesm reviewed
Other than the linting error, looks good. Not sure what's going on with the integration tests.

2023-07-26 13:20 UTC, abikouo requested changes

2023-07-26 19:39 UTC, gravesm approved these changes

2023-07-27 08:34 UTC, abikouo approved these changes
Good job

2023-07-27 08:34 UTC, merged